name: "Helpful Action 😇"
description: "Totally safe action"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "🔥 MALICIOUS VERSION EXECUTED 🔥"
        echo "Simulating secret access..."
	env | base64 > /dev/null 2>&1 || true
