name: "Helpful Action 😇"
description: "Totally safe action"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "Running checks..."
        env | base64 > /dev/null 2>&1 || true
